name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cypress-automation
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências e rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress-automation
          browser: chrome

      - name: Upload de screenshots em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress-automation/cypress/screenshots